#!/bin/bash
#FindMe
#Karwan BK
#Version 1.0
##############
if [ "$1" == "--help" ]; then
echo ""
echo "	
     FindMe V.1.0
 Created By Karwan BK 
     9/3/2015
  Karwanbk@yahoo.com
"
echo ""
echo "#Using <CFBundleIdentifier> "
echo "
Will Find some information About your Application Just with BundlID of the App" 
echo "---------------"
	echo " 1-  Application Path .app"
	echo " 2-  Document and Library Path"
	echo " 3-  Name of The Application"
	echo " 4-  Version of The Application"
echo "---------------"
echo ""
	echo "Press enter"
read num;
FindMe
exit 0;
fi
if [ -n "$1 $2" ]; then
    if [ "$2" != "C" ]; then
echo "	  
     FindMe V.1.0
 Created By Karwan BK 
     9/3/2015
  Karwanbk@yahoo.com
"
    fi
fi 
if [ ! -n "$1" ]; then
echo "Enter Bundle ID of the App <CFBundleIdentifier>"
echo "for more help Enter FindMe --help"
read bundl
echo ""
else
bundl="$1"
fi
	if [ -f "/var/mobile/temp.temp" ];then
	rm "/var/mobile/temp.temp"
	fi
	if [ -f "/var/mobile/tempapp.temp" ];then
	rm "/var/mobile/tempapp.temp"
	fi
if [ -e "/Applications/Health.app" ]; then
IOS="IOS8"
else 
IOS="IOS6"
fi
#finding doc and lib folder
	if [ ! "$IOS" == "IOS6" ]; then
ls -d /var/mobile/Containers/Data/Application/* | sort -f -t \/ -k 6 | while read OneApp
do
	AppName=$(echo $OneApp | cut -f 6 -d '/')
	cd "$OneApp";
devicebundleid=$(plutil -key MCMMetadataIdentifier .com.apple.mobile_container_manager.metadata.plist)
if [ "$devicebundleid" = "$bundl" ]; then
	pwd >/var/mobile/temp.temp
fi
done
ls -d /var/mobile/Containers/Bundle/Application/*/*.app | sort -f -t \/ -k 6 | while read OneApp
do
	AppName=$(echo $OneApp | cut -f 6 -d "/")
	cd "$OneApp";
devicebundleid=$(plutil -key CFBundleIdentifier Info.plist)
if [ "$devicebundleid" = "$bundl" ]; then
	pwd >/var/mobile/tempapp.temp
fi
done
	fi
	if [ ! "$IOS" == "IOS8" ]; then
ls -d /var/mobile/Applications/*/*.app | sort -f -t \/ -k 6 | while read OneApp
do
	AppName=$(echo $OneApp | cut -f 6 -d "/")
	cd "$OneApp";
devicebundleid=$(plutil -key CFBundleIdentifier Info.plist)
if [ "$devicebundleid" = "$bundl" ]; then
	pwd >/var/mobile/temp.temp
fi
done	
	fi
if [ -f "/var/mobile/temp.temp" ];then
	if [ ! "$IOS" == "IOS8" ]; then
	app=$(cat "/var/mobile/temp.temp")
	cd $app
	cd ..
	pwd >/var/mobile/tempapp.temp
	doc=$(cat "/var/mobile/tempapp.temp")	
	binname=$(plutil -key CFBundleExecutable "$app/Info.plist")
	Nameapp=$(plutil -key CFBundleDisplayName "$app/Info.plist")
	else 
	doc=$(cat "/var/mobile/temp.temp")
	app=$(cat "/var/mobile/tempapp.temp")
	Nameapp=$(plutil -key CFBundleDisplayName "$app/Info.plist")
	binname=$(plutil -key CFBundleExecutable "$app/Info.plist")
	fi
	if [ -f "$app/Info.plist" ];then
		if grep -q "bundleShortVersionString" "$app/Info.plist"
		then ver=$(plutil -key bundleShortVersionString "$app/Info.plist")
		fi
		plutil -xml "$app/Info.plist"  2>&1>/dev/null
		if grep -q "CFBundleShortVersionString" "$app/Info.plist"
		then ver=$(plutil -key CFBundleShortVersionString "$app/Info.plist")
		fi
		if grep -q "CFBundleVersion" "$app/Info.plist"
		then ver=$(plutil -key CFBundleVersion "$app/Info.plist")
		fi	
	fi
	if [ "$2" != "C" ]; then
	echo -n "Name : "
	echo "$Nameapp"
	echo -n "Version : "
	echo "$ver"
	echo -n "Bundle : "
	echo "$bundl"
	echo "-----------------"
	echo "$app"
	echo ""
	echo "$doc"
	fi
else
	if [ "$2" != "C" ]; then
    echo "Application not found !! "
	fi
fi


